### ISSUE TITLE
Comparison to `system.addTimer`

### ISSUE THREAD

**Issue by oxisto** [Jericho1060/du-nested-coroutines#1]
Hi there,

I am relatively new to the scripting side of DU and I was wondering what the benefits of this approach are in comparison to setting a timer, e.g. every second. Arent' you generating more load since you are using the `onUpdate` event, which is basically a timer with the interval 0? Just wondering

**Comment by thoda-dev** [comment]
Hi, the system.onUpdate is based on your fps.
if your game is running at 30 FPS, you are calling the function 30 times a second and so on. That system will permit to adapt the timer to your frame rate.

The benefit of co-routines is that case is that you can have a look on the status. It's not doable with timers.
if a function in the coroutine is not ended, the script is not restarting it, it's just waiting it's ended or in pause to continue.
If in a timer, your function is not ended, if the time is reached, it's retsrating it again, and this is increasing each time the timer is triggered.

You don't have to think about "what's the best time for my timer to do the job"

Also, based on how it's done in the game, it always more efficient to use pure lua system than timer system that depends on C libraries that are more heavy.
